### ISSUE TITLE
Architecture Diagram

### ISSUE THREAD

**Issue by bhasin85** [aodn/aws-wps#1]
![gogoduck](https://user-images.githubusercontent.com/2552378/29254005-e17ae5e4-80ce-11e7-979b-58d8977c8b94.png)

**Comment by bhasin85** [comment]
![gogoduck 1](https://user-images.githubusercontent.com/2552378/31265263-ad7daf0a-aab9-11e7-84b9-d1e49cc350fe.png)

**Comment by jonescc** [comment]
Better on wiki?

**Comment by bhasin85** [comment]
readme looks appropriate to me.

**Comment by bhasin85** [comment]
![gogoduck 2](https://user-images.githubusercontent.com/2552378/31866826-12aad776-b7d1-11e7-8da1-eb412763a7a8.png)

**Comment by bhasin85** [comment]
![gogoduck 3](https://user-images.githubusercontent.com/2552378/31866894-aa106b80-b7d1-11e7-8d75-0e8c1305d060.png)

**Comment by jonescc** [comment]
Included in https://github.com/aodn/aws-wps/pull/154
