### ISSUE TITLE
Provenance document issues

### ISSUE THREAD

**Issue by jonescc** [aodn/aws-wps#113]
### To reproduce

Submit valid execute request requesting provenance output

### What happens

Get provenance document with invalid settings location:

```
    <prov:entity prov:id="outputAggregationSettings">
        <prov:location>https://github.com/aodn/geoserver-config/tree/production/https://s3-ap-southeast-2.amazonaws.com/aws-wps-dev-testing/config/templates.xml</prov:location>
        <prov:type codeList="codeListLocation#type" codeListValue="outputConfiguration">outputConfiguration</prov:type>
    </prov:entity>
```

Missing source data location

```
     <prov:entity prov:id="sourceData">
        <prov:location></prov:location>
        <prov:type codeList="codeListLocation#type" codeListValue="inputData">inputData</prov:type>
    </prov:entity>
```

Java documentation link which points to GoGoDuck doco which is now out-of-date

### What I expect to happen

Get correct information included.

**Comment by ccmoloney** [comment]
The missing location for sourceData is a problem with the CatalogueReader class - it doesn't return a value from the getMetadataUrl method.  If we can resolve that - the location will be populated.

**Comment by ccmoloney** [comment]
The first issue is a problem with the freemarker template(provenance_template_non_gridded.ftl)  - which can be easily resolved.

**Comment by akashisama** [comment]
Fixed by https://github.com/aodn/aws-wps/pull/134
