### ISSUE TITLE
Documents not stored on S3 with correct mimetype

### ISSUE THREAD

**Issue by jonescc** [aodn/aws-wps#114]
### To reproduce

Submit a valid execute request and wait for it to complete.  Attempt to download status.xml, request.xml, output files

### What happens

Files are downloaded as content-type application/octet-stream confusing applications that use them (restassured in my instance)

### What I expect to happen

The correct content-type is returned for the downloaded files.

**Comment by ccmoloney** [comment]
This should be resolved by this PR: https://github.com/aodn/aws-wps/pull/116

**Comment by jonescc** [comment]
Sure is.
