### ISSUE TITLE
Unhelpful error returned when requesting an unsupported process

### ISSUE THREAD

**Issue by jonescc** [aodn/aws-wps#119]
### To reproduce

Submit an execute request for an unknown process you get:

### What happens
```
<ExceptionReport version="1.0.0" xmlns="http://www.opengis.net/ows/1.1">
  <Exception exceptionCode="ExecutionError">
    <ExceptionText>Error executing request, Exception : JobDefinition must be provided, RequestId: efd5483a-bf5f-11e7-a61f-794d20532e48 (Service: AWSBatch; Status Code: 400; Error Code: ClientException; Request ID: efd5483a-bf5f-11e7-a61f-794d20532e48)</ExceptionText>
  </Exception>
</ExceptionReport>
```

### What I expect to happen 

Get a more informative error message - such as Unknown process ...

**Comment by ccmoloney** [comment]
I think that this might have been resolved?  There is a unit test that passes a process name of 'unknown' - which returns the exception text "No such process 'unknown'".  Does that cover off this issue?  @jonescc

**Comment by ccmoloney** [comment]
Just tested - no, it doesn't return a sensible message.  Will investigate.

**Comment by ccmoloney** [comment]
Should be resolved by this PR:  https://github.com/aodn/aws-wps/pull/242
