### ISSUE TITLE
Files aggregated out of order

### ISSUE THREAD

**Issue by jonescc** [aodn/aws-wps#121]
### To reproduce 

Submit

[request.txt](https://github.com/aodn/aws-wps/files/1439277/request.txt)

or a smaller subset

### What happens

Files are aggregated in random order

```
Adding /tmp/ee9da36d-626d-424e-8748-3ab7fcb3a05720161126032000-ABOM-L3S_GHRSST-SSTskin-AVHRR_D-1d_day.nc to output file
Adding /tmp/fc578f8c-ab70-49ee-b4a0-cf0188b2610c20170308032000-ABOM-L3S_GHRSST-SSTskin-AVHRR_D-1d_day.nc to output file
Adding /tmp/ec7dc58b-33ed-4700-9c2b-cf39f0afb42e20170630032000-ABOM-L3S_GHRSST-SSTskin-AVHRR_D-1d_day.nc to output file
Adding /tmp/b0b24011-e366-461e-8f81-ca26e8ff789920161129032000-ABOM-L3S_GHRSST-SSTskin-AVHRR_D-1d_day.nc to output file
...
```

### What I expect to happen

Files are added in time order so that the resulting time series is valid.

**Comment by ccmoloney** [comment]
Resolved by PR: https://github.com/aodn/aws-wps/pull/133/files
