### ISSUE TITLE
IAM policies with overly broad Resource: '*' access

### ISSUE THREAD

**Issue by lwgordonimos** [aodn/aws-wps#139]
The following policies need to be modified so that the corresponding role only has access to modify the appropriate stack resource. For example, a Lambda PublishVersion permission should only apply to the stack function (by reference), to avoid any risk of code bugs modifying non-stack resources.

I think these are all of the references to '*':

https://github.com/aodn/aws-wps/blob/master/wps-cloudformation-template.yaml#L542
https://github.com/aodn/aws-wps/blob/master/wps-cloudformation-template.yaml#L647
https://github.com/aodn/aws-wps/blob/master/wps-cloudformation-template.yaml#L749
https://github.com/aodn/aws-wps/blob/master/wps-cloudformation-template.yaml#L783
https://github.com/aodn/aws-wps/blob/master/wps-cloudformation-template.yaml#L882
https://github.com/aodn/aws-wps/blob/master/wps-cloudformation-template.yaml#L1055

**Comment by ccmoloney** [comment]
I think all of these have been addressed.  Closing.
