### ISSUE TITLE
Cloud Formation Resource List

### ISSUE THREAD

**Issue by akashisama** [aodn/aws-wps#14]
Parameters (values you pass in when you bring up a new stack):
- vpc subnets
- vpc security group
- geoserver address
- job vCPUs
- job memory
- pre-existing S3 bucket for output (optional)
- docker image
- lambda function S3 bucket
- lambda function S3 key

Created Resources:
Job definition + IAM role
Job Queue
Compute Environment + IAM role
Lambda Handler + IAM role
S3 Bucket for output (if no pre-existing bucket given)
API Gateway

**Comment by ccmoloney** [comment]
Environment variables - 

Lambda:
    AWS_BATCH_JOB_QUEUE_NAME
    GET_CAPABILITIES_TEMPLATE_S3_BUCKET
    GET_CAPABILITIES_TEMPLATE_S3_KEY
    DESCRIBE_PROCESS_S3_BUCKET
    DESCRIBE_PROCESS_S3_KEY_PREFIX
    OUTPUT_S3_FILENAME
    OUTPUT_S3_BUCKET
    AWS_BATCH_JOB_NAME
    GEOSERVER_WPS_ENDPOINT_URL
    STATUS_S3_BUCKET
    STATUS_S3_BUCKET

AWS Batch Job Definition:
    OUTPUT_S3_FILENAME
    OUTPUT_S3_BUCKET
    STATUS_S3_BUCKET
    STATUS_S3_BUCKET

**Comment by akashisama** [comment]
Closing as out of date.
