### ISSUE TITLE
Update GoGoDuck endpoint URLs in Geonetwork for AWS-WPS switchover

### ISSUE THREAD

**Issue by ccmoloney** [aodn/aws-wps#146]
As part of our switch-over procedure for promoting the new AWS gs:GoGoDuck implementation into production - we will need to update the metadata records for all relevant records to point to the new AWS WPS endpoint.

WPS endpoints for NetcdfOutput will remain as they are - ie: pointing to the Geoserver WPS endpoint.

It has been suggested (by @jonescc ) that updating these metadata records could possibly be scripted in some fashion.

**Comment by ccmoloney** [comment]
Can you please provide details of the script to update these metadata records + close please @anguss00

**Comment by anguss00** [comment]
Pretty sure this is the commit @ccmoloney https://github.com/aodn/schema-plugins/commit/3b2caaa6495aaa09c208313c176853c7ebbc01dd. Allows a wms endpoint url to be passed as a parameter. We need to update the harvesters to use the new transform with the additional param

**Comment by jonescc** [comment]
While not updating the netcdf-subset-service link?

**Comment by anguss00** [comment]
OK, sorry my bad. Just to clarify, is this transform for the sandbox environment? Because I have fixed that sandbox transform to update the URLs except for the netcdf-subset-service

**Comment by anguss00** [comment]
https://github.com/aodn/schema-plugins/blob/master/iso19139.mcp-2.0/process/transform_sandbox_urls.xsl

**Comment by ccmoloney** [comment]
It needs to be run in each environment we roll the AWS-WPS codebase into - to redirect WPS GoGoDuck requests to the AWS Lambda endpoint associated with that environment.

**Comment by pblain** [comment]
This is done according to @ccmoloney
