### ISSUE TITLE
Status Page Improvements

### ISSUE THREAD

**Issue by ccmoloney** [aodn/aws-wps#163]
During the last iteration I prototyped some additions to the status page - aimed at providing support information.  The aims of these additions were to:

- Give a view of what was in the AWS Batch queue : to allow us to see how many jobs were queued, what jobs are currently running & what jobs have been completed recently (the job information is only available in AWS Batch for approximately 24 hours after a job has completed processing).
- Provide additional information about each individual job that may be useful for support.  In the first instance I have added the ability to view the request that was submitted : which shows the layer, the subset requested, the email address of the user who requested the aggregation & the outputs requested.

The initial prototype has added 2 new 'format's to the status page that can be requested to view this additional information:
    format=queue  :  Displays the queue information
    format=admin&jobId=<JOB_ID> : shows the job status and the request information for the job

**Comment by ccmoloney** [comment]
Example of format=admin:

![image](https://user-images.githubusercontent.com/30034813/33403329-1336c532-d5b4-11e7-926c-f8ab14e59267.png)

**Comment by ccmoloney** [comment]
Example of format=queue:

![image](https://user-images.githubusercontent.com/30034813/33403355-2e281b48-d5b4-11e7-95ec-9c4d53d2acd3.png)

**Comment by ccmoloney** [comment]
Improvements identified so far:

-  Job ID values on the Queue view page should link to the status page for that job (wither the regular HTML status or the admin status page)
-  Ordering of the jobs should default to time order
-  User should be able to sort the tables by clicking on the header fields.
-  Formatting of timestamps should be briefer format (maybe HH:MM:ss dd/MM/YYYY?)
-  Admin status page could contain links to the CloudWatch logs (if the job is RUNNING or completed)
-  General HTML formatting.  Table needs some styling by modifying AODNTheme.css

**Comment by pmbohm** [comment]
- Could you make the background header and footer colour #1c384a
- What about a page header, a link back to the portal, link IMOS web page?

**Comment by ccmoloney** [comment]
This is a link to a current version - i think the header/footer is sorted.
https://wps2.dev.aodn.org.au/wps/jobStatus?jobId=d43d678d-4050-4567-ab3f-fcec4e6291b4&format=admin

AND

https://wps2.dev.aodn.org.au/wps/jobStatus?jobId=d43d678d-4050-4567-ab3f-fcec4e6291b4&format=queue

**Comment by pmbohm** [comment]
Heres what you need for the status page. Includes table styling
[status.css.txt](https://github.com/aodn/aws-wps/files/1516507/status.css.txt)

**Comment by ccmoloney** [comment]
The current implementation reflects the styling of the status page we currently display in production.  If we want to re-style the page, we should consult the product owner (@pblain) & get it added as an improvement in the backlog.  We could apply the table style updates - but it think restyling the header & footer should be discussed with Pete.

**Comment by pmbohm** [comment]
@ccmoloney So what your saying is you will use the table styling that has not been used anywhere before??, but you wont get rid of the grey header which makes the AODN hard to see and also is vastly different from the AODN portal???

Its no fancy change, its from a grey background to a blue background similar to portal

**Comment by ccmoloney** [comment]
I'm saying I don't care if it's pink with purple dots.  Pete might care though  :)

**Comment by ccmoloney** [comment]
Another possible improvement:

- Tidy up the view of the request XML in the ADMIN view for a job.  Maybe make that section collapsible.  Currently it is displayed in a textarea - which takes up quite a lot of screen real-estate & pushes the log link off the page (have to scroll to see it).

**Comment by pmbohm** [comment]
@ccmoloney https://github.com/aodn/aodn-portal/issues/2585 is actually only fixable in this repo

**Comment by ccmoloney** [comment]
Yep - it's an AWS WPS issue.

**Comment by ccmoloney** [comment]
All improvements identified have been implemented to this point.
