### ISSUE TITLE
Remove deleted inputs from aws_wps_deploy job

### ISSUE THREAD

**Issue by jonescc** [aodn/aws-wps#174]
getCapabilitiesURL, jobStatusHtmlTransformURL, jobQueueHtmlTemplateURL, gogduckURL, netcdfOutputURL, templatesURL, provenanceTemplateGriddedURL, provenanceTemplateNonGriddedURL

parameters have been removed from the cloud formation template and do not need to be supplied anymore.

To be removed after all prior versions of the cloud formation template using it have been deployed.

**Comment by ccmoloney** [comment]
I think @lwgordonimos has removed all of these in his numerous tidy-up-the-template pull requests...

**Comment by jonescc** [comment]
Yep, fixed under https://github.com/aodn/backlog/issues/741
