### ISSUE TITLE
Location of Stuff

### ISSUE THREAD

**Issue by akashisama** [aodn/aws-wps#2]
I was initially having trouble working out which folders in the repo connected with with which aws services. The services are located in the US East N. Virginia region (us-east-1).

- ```javaduck-image```  contains a docker file which is used with the Elastic Container Service (ECS). The created instances will contain the "aggregation-worker "jar so aggregations can be performed from them.

- ```aggregation-worker``` contains the java code from which the "aggregation-worker" jar has been compiled. This is the same code as in the geoserver javaduck extension (probably with some small changes) and performs the grunt work of the aggregation.

- ```request-handler```  contains the lambda function code for adding a batch job. The batch details are currently hard coded in:
```
        SubmitJobRequest submitJobRequest = new SubmitJobRequest();
        submitJobRequest.setJobQueue("javaduck-small-in");  //TODO: config/jobqueue selection
        submitJobRequest.setJobName("javaduck");
        submitJobRequest.setJobDefinition(processIdentifier);  //TODO: either map to correct job def or set vcpus/memory required appropriately
        submitJobRequest.setParameters(parameterMap);

        AWSBatchClientBuilder builder = AWSBatchClientBuilder.standard();
        builder.setRegion("us-east-1");  // TODO: get from config
```

- ```requests``` contains a demo request to an API gateway, which simply proxies the request to the lambda function. There doesn't seem to be any code for the definition of the gateway yet, it's been set up manually.

**Comment by jonescc** [comment]
Better on wiki or in a readme?

**Comment by jonescc** [comment]
included in https://github.com/aodn/aws-wps/pull/154
