### ISSUE TITLE
Loggargeddon! (AWS Batch Logging is dumb)

### ISSUE THREAD

**Issue by ccmoloney** [aodn/aws-wps#206]
We have a couple of problems relating to the way that AWS Batch logs all log stream for batch jobs into a fixed /aws/batch/jobs logging group.  I have investigated whether it is possible to get different stacks to log into different logging groups for their batch jobs - but this is not possible (as far as i can tell at this stage).

Logs for a batch job running create a log stream under the /aws/batch/jobs group - with the log stream name beginning with the JobDefinitionName for the running job (JavaDuckSmall1-alexs-stack/default/1da7d468-f0f7-40b4-bd44-9e8f100356da for instance).  This seems semi-sensible at the start - but as you actually think about it now you realise that it is actually an abomination!!!

The problems start when you want to set up a subscription on batch logs so that your environment can, say, trigger a lambda function based on CloudWatch logs - exactly what we want to do to invoke our SumoLogic lambda function to send log entries to Sumo for reporting etc.  There is a hard limitation for some reason that only one subscription can be registered against a log group.  This means that ONLY ONE STACK PER ACCOUNT can set up the sumo lambda trigger to send its logs to Sumo.

That's cool you say.  We'll just have one subscription - no worries.

The problem then is that say production is the stack that has it's log subscription registered to send logs to Sumo.  Cool....except that in the production AWS account we have also run up sandbox and systest environments....and...THEY ALL LOG TO THE /aws/batch/jobs LOG GROUP!!

So: our lovely production log subscription lambda thingy is sending not only the batch job logs for production - but also all the batch logs for sandbox and systest.

We can change the Sumo lambda function to be more selective about the logs it sends - ie: send only logs with a log stream name which contains the stack name.  This would ensure that the active subscription only sends logs from the stack which registered the subscription.  But: no other stacks in the account can send any batch logs - which is a bit limiting, because we will often want to test out logging changes and metric-gathering in systest before going to production.

**Comment by lwgordonimos** [comment]
One other option would be to drop the logs into S3 and have Sumo read from there. This is how it currently reads access logs for the imos-data bucket, because that is how it archives its logs.

It would require a scheduled Lambda to make the following call: http://docs.aws.amazon.com/cli/latest/reference/logs/create-export-task.html, which would add an async task to put the logs into the bucket, which Sumo can then pick up.

Obviously less appealing than a subscription model, but the server side async nature and the native Sumo support for S3 makes it not completely horrible...

**Comment by pmbohm** [comment]
"our lovely production log subscription lambda thingy is sending not only the batch job logs for production - but also all the batch logs for sandbox and systest."

We can identify the prod environment at the Sumo query cant we?

**Comment by ccmoloney** [comment]
Only by looking at the logStream value - which should contain the stack name (only by convention - because we include the stack name in the batch job definition name - the log stream name starts with the batch job defintion name).  Example logStream name:  JavaDuckSmall1-aws-wps-sandbox/default/3471ee05-8bf2-44b9-9355-17e6236fbbd0

**Comment by pmbohm** [comment]
```
_sourceCategory=AWS/WPS/Sandbox
AND _sourcename =JavaDuckSmall1-cam-test*
```

**Comment by ccmoloney** [comment]
Yep - entirely possible.  The issue is more that we would have liked for each environment to log it's output into separate sourceCategories to make it more logical in Sumo.  And - we were setting up the Sumo log sending function in the cloudformation for a stack - so each stack would set up its own.  Because of the limitations of the way they have done batch logging - we can only ever have one stack subscribe to the /aws/batch/jobs log group.  So: it's just harder to manage it.

**Comment by ccmoloney** [comment]
Options currently identified are:

**Option 1 -**
Only enable the Sumo lambda function in one stack per account.  If we only specify a sumo endpoint for one of the stacks we create in an account - then that stack will currently send all of the batch logs for that account to the specified sumo endpoint.  

Pros:
Only small changes required to our stack creation template to pass a boolean flag to the cloudformation - which indicates that the stack is to subscribe to the batch log group and send those logs to a sumo endpoint & a batch log sumo endpoint URL parameter - so that the batch logs can be sent to a specific collector in sumo.

Cons:
- All batch logs for all stacks in the account will be sent to the same sumo collector - and will, therefore, all appear in sumo with the same sourceCategory.  Logs from different stacks can be differentiated on the Sumo side by looking at the logStreamName - which contains the stack name.  This means that we could technically perform the searches we need to (I think) - it just makes those searches a bit messier.
- We have to manually manage which stack is sending the batch logs (by making sure one stack is configured to send them).
- Stack creation will fail for any subsequent stacks which are configured to send batch log - due to the limitation of only one subscription being allowed on any given log group.

**Option 2 -**
Manage the sumo lambda function in its own stack - one of which is run up in each account.  Modify the current sumo lambda function to send batch log streams to different endpoints based on which stack generated them.

Pros:
- Will result in the logs ending up in Sumo in the target state - ie: all logs (request handler, status service & batch) for a stack sent to a single sumo collector & having the same sourceCategory.
- Makes Sumo searches easier & less chance of metrics being 'polluted' by log messages from different stacks.

Cons:
- Development effort to modify the sumo lambda function code
- Need to devise a way to configure the function to associate a sumo endpoint with each stack (based on the stack name probably) & manage that configuration.
- Need to update the configuration manually & update the sumo lambda when new stacks are created (mostly a problem if we want to send logs from dev environments to sumo - so not that likely).

**Comment by ccmoloney** [comment]
**Option 4-**
Modify the current Sumo lambda code to assign the X-Sumo-Category HTTP header for logs generated by the /aws/batch/job log group.  This header seems to specify a desired sourceCategory for the log message - so we can essentially tell sumo what sourceCategory we want assigned to messages based on the stream name (which contains the stack name) when it is sending logs to Sumo.  We could come up with a simple convention like WPS/Batch/<stack_name> or something : or we could get a bit more sophisticated and send them to the same sourceCategory as the requestHandler logs (WPS/Sandbox, WPS/Systest, WPS/Production).

Pros:
- Only small modification required to the sumo lambda code.

Cons:
-Doesn't solve the problem of only one log subscription being allowed.

**Comment by lwgordonimos** [comment]
Looks like a good rundown.

Option 1 - I think this is not feasible. Having strange infrastructure singletons that break other stacks is a recipe for so many headaches it gives me a headache just thinking about.

Option 2 - I don't think it's a huge problem having this in a separate per-account stack, less evil than some other options anyway. I do think modifying the upstream code should be avoided at all costs however, so if that is required, not a fan of this option either.

Option 3 - This is probably the cleanest to be honest, as it stands (second only to the log group being configurable), but extra accounts are only cheap in terms of maintenance if they are 100% Cloudformation managed (from the ground up), which we aren't quite there yet.

Option 4 - See Option 2 re: modifying the Lambda code

Not sure any option is any good as you said :(

* we really don't want to fork the Lambda function, but given the options, if this really is the "lesser of all the evils", it's better than making the infrastructure flaky with side effects on other stacks
* we really need different environments going into different Sumo source categories... I think this is mandatory, otherwise we're just moving the dirty hacks to somewhere else in the chain

What we really, really, really want is for the log group to be configurable! Can we hound AWS any more about this horrible omission in the Batch product?

**Comment by ccmoloney** [comment]
I agree - we are definitely just looking at the least evil option until they allow log group to be specified for job definitions.  I have raised a query on the batch support form - we'll see what they come back with.
For reference:
https://forums.aws.amazon.com/thread.jspa?messageID=822175#822175

**Comment by ccmoloney** [comment]
**Option 5-**

Send logs directly from our aggregator java code to a specified Sumo endpoint.  Ultimately the logs are just sent as HTTP messages formed by the Sumo Lambda function.  We could get the Java code running in the batch docker image to send the batch log messages directly - and not rely on the log subscription mechanism.

It might actually be possible to configure a log4j appender or something to do the sending.  If not - there seems to be some client code provided by Sumo (https://github.com/SumoLogic/sumo-log4j-appender/blob/master/src/main/java/com/sumologic/log4j/http/SumoHttpSender.java) that we could use.

**Comment by jonescc** [comment]
I like this  (Option 5) - removes sumologic lambda function management and provides a consistent way of logging to sumo which is completely under our control.   Can still push logs to cloudwatch but aren't constrained by the limitations there.

**Comment by ccmoloney** [comment]
Implementing option 5 - which seems to work pretty well.  There is one outstanding issue - which is to do with a buffer of messages which isn't getting flushed reliably when the VM shuts down at the end of the batch aggregation. 

I will raise an issue to track a fix for it (although what i have implemented is probably sufficient for now - all the significant log messages are being written to sumo).

**Comment by ccmoloney** [comment]
Considering this closed - with a follow on issue raised here:  https://github.com/aodn/aws-wps/issues/217

**Comment by duchatran** [comment]
This is Duc from Sumo Logic. I run into this thread just now, very interesting use case. I want to add that one can also setup a Field Extraction Rule  on Sumo side to overwrite the sourceCategory at ingestion, that way no Lambda code change is needed. Of course this won't help if you want each stack to setup its own collection - the blocking issue there is you can only have 1 subscription for a CloudWatch log group.
