### ISSUE TITLE
Missing date value for CARS World Monthly time series at a point

### ISSUE THREAD

**Issue by jonescc** [aodn/aws-wps#208]
### To reproduce

Submit the following request to AWS Batch (using your own email address):

[request.txt](https://github.com/aodn/aws-wps/files/1596563/request.txt)

### What happens

When I download the resulting csv file the last 5 entries should be for 1/1/10 but no date value is shown:

![image](https://user-images.githubusercontent.com/1860215/34472324-af7ea4a0-efb3-11e7-86b7-21438a3b3a51.png)

### What I expect to happen

All date values are shown

**Comment by jonescc** [comment]
Note, this also occurs in prod geoserver-wps so this is not a bug introduced with AWS batch implementation.

**Comment by jonescc** [comment]
The reason why these values aren't being displayed is because they are invalid according to the definition of the variable and so are considered missing data by the netcdf library.   DAY_OF_YEAR is defined as a short int with valid_max = 365, but the value is actually 366.   This is a content issue.

**Comment by kereid** [comment]
Bump

I think this may have caused a download to fail on Friday for a user, I have repeated the download in systest today with the same error (if not let me know and I'll open a separate issue):

Exception occurred during aggregation :For input string: "${Z_MAX}"


<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:Execute service="WPS" version="1.0.0" xmlns:ns2="http://www.opengis.net/wps/1.0.0" xmlns:ns1="http://www.opengis.net/ows/1.1" xmlns:ns3="http://www.w3.org/1999/xlink">
    <ns1:Identifier>gs:GoGoDuck</ns1:Identifier>
    <ns2:DataInputs>
        <ns2:Input>
            <ns1:Identifier>layer</ns1:Identifier>
            <ns2:Data>
                <ns2:LiteralData>csiro_cars_monthly_url</ns2:LiteralData>
            </ns2:Data>
        </ns2:Input>
        <ns2:Input>
            <ns1:Identifier>subset</ns1:Identifier>
            <ns2:Data>
                <ns2:LiteralData>TIME,2009-01-01T00:00:00.000Z,2009-12-03T00:00:00.000Z;LATITUDE,-16.3964,-16.3964;LONGITUDE,122.9275,122.9275</ns2:LiteralData>
            </ns2:Data>
        </ns2:Input>
        <ns2:Input>
            <ns1:Identifier>callbackUrl</ns1:Identifier>
            <ns2:Data>
                <ns2:LiteralData>
                    https://portal-systest.aodn.org.au/wps/jobComplete
               </ns2:LiteralData>
            </ns2:Data>
        </ns2:Input>
        <ns2:Input>
            <ns1:Identifier>callbackParams</ns1:Identifier>
            <ns2:Data>
                <ns2:LiteralData>email.to=kate.reid@utas.edu.au</ns2:LiteralData>
            </ns2:Data>
        </ns2:Input>
    </ns2:DataInputs>
    <ns2:ResponseForm>
        <ns2:ResponseDocument storeExecuteResponse="true" status="true">
            <ns2:Output asReference="true" mimeType="text/csv">
                <ns1:Identifier>result</ns1:Identifier>
            </ns2:Output>
        </ns2:ResponseDocument>
    </ns2:ResponseForm>
</ns2:Execute>

**Comment by kereid** [comment]
I added my comment to the wrong issue I'm just going to open a new issue now in content
