### ISSUE TITLE
AWS Batch Sumo logging improvements/fixes

### ISSUE THREAD

**Issue by ccmoloney** [aodn/aws-wps#217]
Sumo logging has been implemented (yet to be merged) using the sumologic log4j2 appender (https://github.com/SumoLogic/sumologic-log4j2-appender).

During testing I have noticed that on shutdown of the AWS batch aggregation process (we exit using System.exit calls at the end of the process) that some log messages are not flushed to Sumo.  By tinkering with various settings (messagesPerRequest) I have ensured that the significant log messages (messages we use for detecting the end of aggregations) are being logged - but there doesn't appear to be any way of absolutely guaranteeing that all log messages are sent.

I have raised an issue in github against the sumo log4j2 project to seek clarification and a fix:
https://github.com/SumoLogic/sumologic-log4j2-appender/issues/8

I have raised this ticket to track a fix for this issue should one need to be applied once a resolution is forthcoming from sumologic.

Ideally the sumo appender would flush all pending messages on shutdown of the VM - or would provide some way to explicitly flush them that we could invoke before shutting down the batch VM.

**Comment by jonescc** [comment]
I don't think we need to use System.exit(0) at the end of the process - Should exit with that status anyway?

**Comment by ccmoloney** [comment]
Yeah - we probably don't need to.  I could see if not exiting explicitly makes any difference...

**Comment by jonescc** [comment]
No harm in removing it anyway.

**Comment by ccmoloney** [comment]
Closing this as the current implementation reliably logs all messages that we need to form our Sumo stats.
