### ISSUE TITLE
No error returned if template file can't be found

### ISSUE THREAD

**Issue by jonescc** [aodn/aws-wps#221]
### To reproduce 

Run up an aws-wps stack with a templateUrl which is not resolvable and request an aggregation to be performed

### What happens

A log message is written indicating there was an error trying to read the config file, but the aggregation continues with no overrides applied.

### What I expect to happen

An OGC exception is thrown as the aggregation performed will not be correct/or fail.  This is critical config which needs to be present for aws/wps to work correctly.

**Comment by ccmoloney** [comment]
Should be resolved by PR:  https://github.com/aodn/aws-wps/pull/223
