### ISSUE TITLE
XML status response invalid

### ISSUE THREAD

**Issue by jonescc** [aodn/aws-wps#236]
### To reproduce

Request xml status for an executing job

### What happens

Get an object reference and not an xml response

### What I expect to happen

Get an xml response with the status of the request

**Comment by jonescc** [comment]
e.g. for https://wps-edge.dev.aodn.org.au/wps/jobStatus?jobId=66681106-e808-4433-92f9-826fd63e469c&format=XML

I got:

````  
net.opengis.wps.v_1_0_0.ExecuteResponse@5491f68b
````

**Comment by jonescc** [comment]
Note:  this is the cause of the integration test failure reported last week.

**Comment by ccmoloney** [comment]
Should now be resolved by recent commits.
