### ISSUE TITLE
Status xml should point at new job status xml service if we want to see queue updates

### ISSUE THREAD

**Issue by jonescc** [aodn/aws-wps#76]
### To reproduce

Submit an execute using curl

### What happens 

Get a status response back that points to the s3 file containing the status document

### What I expect to happen

Get a status response back that points to the xml getstatus service for the job.

**Comment by bhasin85** [comment]
We will need to update the portal code to link to HTML instead of xml status page. Current response points the the s3 file instead of the status service.

**Comment by ccmoloney** [comment]
Will be resolved by this PR:  https://github.com/aodn/aws-wps/pull/127

**Comment by jonescc** [comment]
Resolved by #127

**Comment by ccmoloney** [comment]
Resolved by PR: https://github.com/aodn/aws-wps/pull/127
