### ISSUE TITLE
New HTML Status page should look and operate similar to existing status page

### ISSUE THREAD

**Issue by jonescc** [aodn/aws-wps#77]
### To Reproduce

Request new status page

### What happens

 * Displays but with logo missing and formatting not quite right:

![image](https://user-images.githubusercontent.com/1860215/31693320-aee44802-b3e9-11e7-8221-aa639d107b04.png)

* job id links to status.xml on s3
* download link links to status.xml on s3

### What I expect to happen

Looks and operates similar to existing page.

**Comment by ccmoloney** [comment]
Resolved by pull request #111: https://github.com/aodn/aws-wps/pull/111
