### ISSUE TITLE
Email link not working when specifying hostedZoneName/wpsDomainName

### ISSUE THREAD

**Issue by jonescc** [aodn/aws-wps#84]
### To reproduce

Run up a stack specifying hostedZoneName/wpsDomainName(I used dev.aodn.org.au/aps-testing)

Submit a valid Execute request

### What Happens

I get an email with a link to the status page which doesn't work - https://wps-testing.dev.aodn.org.au/wps/jobStatus?jobId=02944aad-dfb5-4b97-8618-958063701559&format=HTML

The actual required link is https://wps-testing.dev.aodn.org.au/LATEST/wps/jobStatus?jobId=02944aad-dfb5-4b97-8618-958063701559&format=HTML

### What I expect to happen

The link should work - i.e. https://wps-testing.dev.aodn.org.au/wps/jobStatus?jobId=02944aad-dfb5-4b97-8618-958063701559&format=HTML   (don't see why we would need to specify LATEST in our url's).

**Comment by bhasin85** [comment]
Related to https://github.com/aodn/aws-wps/issues/92
