### ISSUE TITLE
Cannot update lambda code using cloud formation

### ISSUE THREAD

**Issue by jonescc** [aodn/aws-wps#85]
### To reproduce

Deploy stack with 

```
requestHandlerFilename=request-handler.zip
requestHandlerCodeURL=https://s3-ap-southeast-2.amazonaws.com/wps-lambda/request-handler-testing-3-lambda-package.zip
jobStatusFilename=job-status.zip
jobStatusCodeURL=https://s3-ap-southeast-2.amazonaws.com/wps-lambda/job-status-service-testing-3-lambda-package.zip
```

Try to update stack using

```
requestHandlerFilename=request-handler-4.zip
requestHandlerCodeURL=https://s3-ap-southeast-2.amazonaws.com/wps-lambda/request-handler-testing-4-lambda-package.zip
jobStatusFilename=job-status-4.zip
jobStatusCodeURL=https://s3-ap-southeast-2.amazonaws.com/wps-lambda/job-status-service-testing-4-lambda-package.zip
```

### What happens
Get cloud formation errors:

13:30:04 UTC+1100	UPDATE_FAILED	AWS::Lambda::Function	JobStatusLambdaFunction	Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist.
13:30:03 UTC+1100	UPDATE_FAILED	AWS::Lambda::Function	RequestHandlerLambdaFunction
Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist.

### What I expect to happen

Code is updated and update completes

**Comment by bhasin85** [comment]
https://github.com/aodn/aws-wps/pull/135
